services:
  - type: web
    name: goalstracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn goalstracker.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: goalstracker.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
