# Generated by Django 5.2 on 2025-05-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
